# Generated by Django 5.1.6 on 2025-02-21 17:47

import socialmedia_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=socialmedia_app.models.post_image),
        ),
    ]
